# Generated by Django 5.0.7 on 2024-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_is_available_for_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
